# Generated by Django 6.0.5 on 2026-06-02 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Espacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("interior_climatizado", "Interior · Climatizado"),
                            ("exterior_tropical", "Exterior · Tropical"),
                            ("exterior_cubierto", "Exterior Cubierto · Vista al Mar"),
                            ("interior_versatil", "Interior · Versátil"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("capacidad_max", models.PositiveIntegerField()),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("publicado", "Publicado"), ("borrador", "Borrador")],
                        default="publicado",
                        max_length=15,
                    ),
                ),
                (
                    "imagen_principal",
                    models.ImageField(blank=True, null=True, upload_to="espacios/"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Etiquetas separadas por ·",
                        max_length=200,
                    ),
                ),
                (
                    "color_card",
                    models.CharField(
                        default="#C9A96E",
                        help_text="Color hex de la tarjeta",
                        max_length=20,
                    ),
                ),
                ("eventos_por_dia", models.PositiveSmallIntegerField(default=1)),
                (
                    "ubicacion",
                    models.CharField(default="Complejo Riviera Maya", max_length=100),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Espacio",
                "verbose_name_plural": "Espacios",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Paquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("premium", "Premium"),
                            ("lujo", "Lujo"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("descripcion_corta", models.CharField(max_length=150)),
                ("duracion_horas", models.PositiveSmallIntegerField()),
                (
                    "precio_por_persona",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("es_mas_popular", models.BooleanField(default=False)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Paquete",
                "verbose_name_plural": "Paquetes",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ServicioAdicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_tipo",
                    models.CharField(
                        choices=[
                            ("fijo", "Precio fijo"),
                            ("por_persona", "Por persona"),
                        ],
                        default="fijo",
                        max_length=15,
                    ),
                ),
                (
                    "icono_nombre",
                    models.CharField(blank=True, default="sparkles", max_length=50),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Servicio Adicional",
                "verbose_name_plural": "Servicios Adicionales",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="EspacioCaracteristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=150)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracteristicas",
                        to="venues.espacio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Característica de Espacio",
                "verbose_name_plural": "Características de Espacio",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="EspacioImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="espacios/galeria/")),
                ("caption", models.CharField(blank=True, max_length=100)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="venues.espacio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Espacio",
                "verbose_name_plural": "Imágenes de Espacio",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="PaqueteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=150)),
                ("incluido", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="venues.paquete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Paquete",
                "verbose_name_plural": "Items de Paquete",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="FechaOcupada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("reserva", "Reserva"),
                            ("bloqueo", "Bloqueo administrativo"),
                        ],
                        default="reserva",
                        max_length=10,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=200)),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fechas_ocupadas",
                        to="venues.espacio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fecha Ocupada",
                "verbose_name_plural": "Fechas Ocupadas",
                "unique_together": {("espacio", "fecha")},
            },
        ),
    ]
