# Generated by Django 6.0.5 on 2026-06-02 07:30

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=bookings.models.generar_codigo,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("boda", "Boda"),
                            ("xv_anos", "XV años"),
                            ("bautizo", "Bautizo"),
                            ("aniversario", "Aniversario"),
                            ("empresarial", "Empresarial"),
                            ("cumpleanos", "Cumpleaños"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("num_invitados", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("confirmada", "Confirmada"),
                            ("pendiente_liquidacion", "Pendiente liquidación"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="confirmada",
                        max_length=25,
                    ),
                ),
                (
                    "total_evento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "anticipo_pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notas_internas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coordinador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_coordinados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="venues.espacio",
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="venues.paquete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PagoRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_pago", models.DateField()),
                (
                    "concepto",
                    models.CharField(
                        choices=[
                            ("anticipo", "Anticipo 25%"),
                            ("liquidacion", "Liquidación"),
                            ("extra", "Cargo extra"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="bookings.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="ActividadReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividad",
                        to="bookings.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservaServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveSmallIntegerField(default=1)),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="bookings.reserva",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="venues.servicioadicional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio de Reserva",
                "verbose_name_plural": "Servicios de Reserva",
                "unique_together": {("reserva", "servicio")},
            },
        ),
    ]
